import { Card, Deck } from "@/data/RealmStorage";

const fullDeck: Deck = {
  cards: [
    { value: 1, suit: "Spade", name: "Sid" },
    { value: 2, suit: "Spade", name: "Sign" },
    { value: 3, suit: "Spade", name: "Sum" },
    { value: 4, suit: "Spade", name: "Saw" },
    { value: 5, suit: "Spade", name: "Seal" },
    { value: 6, suit: "Spade", name: "Sash" },
    { value: 7, suit: "Spade", name: "Sock" },
    { value: 8, suit: "Spade", name: "Safe" },
    { value: 9, suit: "Spade", name: "Soap" },
    { value: 10, suit: "Spade", name: "Saz" },
    { value: 11, suit: "Spade", name: "Spade" },
    { value: 12, suit: "Spade", name: "Steam" },
    { value: 13, suit: "Spade", name: "Sing" },
    { value: 1, suit: "Club", name: "Cat" },
    { value: 2, suit: "Club", name: "Can" },
    { value: 3, suit: "Club", name: "Comb" },
    { value: 4, suit: "Club", name: "Car" },
    { value: 5, suit: "Club", name: "Coal" },
    { value: 6, suit: "Club", name: "Cash" },
    { value: 7, suit: "Club", name: "Cake" },
    { value: 8, suit: "Club", name: "Cuff" },
    { value: 9, suit: "Club", name: "Cup" },
    { value: 10, suit: "Club", name: "Case" },
    { value: 11, suit: "Club", name: "Club" },
    { value: 12, suit: "Club", name: "Cream" },
    { value: 13, suit: "Club", name: "King" },
    { value: 1, suit: "Heart", name: "Hat" },
    { value: 2, suit: "Heart", name: "Hen" },
    { value: 3, suit: "Heart", name: "Ham" },
    { value: 4, suit: "Heart", name: "Hare" },
    { value: 5, suit: "Heart", name: "Hell" },
    { value: 6, suit: "Heart", name: "Hedge" },
    { value: 7, suit: "Heart", name: "Hag" },
    { value: 8, suit: "Heart", name: "Hive" },
    { value: 9, suit: "Heart", name: "Hoop" },
    { value: 10, suit: "Heart", name: "Hose" },
    { value: 11, suit: "Heart", name: "Heart" },
    { value: 12, suit: "Heart", name: "Queen" },
    { value: 13, suit: "Heart", name: "Hinge" },
    { value: 1, suit: "Diamond", name: "Date" },
    { value: 2, suit: "Diamond", name: "Dane" },
    { value: 3, suit: "Diamond", name: "Dome" },
    { value: 4, suit: "Diamond", name: "Door" },
    { value: 5, suit: "Diamond", name: "Doll" },
    { value: 6, suit: "Diamond", name: "Dish" },
    { value: 7, suit: "Diamond", name: "Duck" },
    { value: 8, suit: "Diamond", name: "Dove" },
    { value: 9, suit: "Diamond", name: "Dope" },
    { value: 10, suit: "Diamond", name: "Dice" },
    { value: 11, suit: "Diamond", name: "Diamond" },
    { value: 12, suit: "Diamond", name: "Dream" },
    { value: 13, suit: "Diamond", name: "Drink" },
  ] as Card[],
} as Deck;

export { fullDeck };
